fix: missing read lock in MapWithTTL (#1445)
## Which problem is this PR solving?

```
fatal error: concurrent map read and map write

goroutine 193 [running]:
github.com/honeycombio/refinery/generics.(*MapWithTTL[...]).SortedValues(0xdd8a60)
	github.com/honeycombio/refinery/generics/mapttl.go:118 +0xcc
github.com/honeycombio/refinery/internal/peer.(*RedisPubsubPeers).Ready.func1()
	github.com/honeycombio/refinery/internal/peer/pubsub_redis.go:212 +0x454
created by github.com/honeycombio/refinery/internal/peer.(*RedisPubsubPeers).Ready in goroutine 1
	github.com/honeycombio/refinery/internal/peer/pubsub_redis.go:180 +0x84

```

## Short description of the changes

- add `RLock` for `SortedValues`